#!/usr/bin/env ansible-playbook
---
- name: Installs ZFS On Linux
  hosts: node0
  become: true
  roles:
    - role: ../cjsteel.zfs
      vars:
        # zfs_create_filesystems: false
        zfs_create_pools: true
        zfs_create_volumes: false
        zfs_enable_auto_snapshots: false
        zfs_enable_iscsi: false
        # Defines if NFS Kernel Server should be installed to serve NFS
        zfs_enable_nfs: true
        # Defines if paramaters defined in zfs_performance_tuning are applied
        zfs_enable_performance_tuning: false
        # Defines if Samba is installed and configured
        zfs_enable_samba: false
        # Defines filesystems to manage
        zfs_filesystems:
          - name: nfs
            pool: tank
            atime: off
            # on | off (default) | lzjb | gzip | gzip-1 | gzip-2 | gzip-3 | gzip-4 | gzip-5 | gzip-6 | gzip-7 | gzip-8 | gzip-9 | lz4 | zle
            compression: lz4
            # latency (default) | throughput
            logbias: latency
            # Define an alternate mountpoint
            mountpoint: /tank/nfs # /var/lib/docker
            # all (default) | none | metadata
            primarycache: all
            quota: 3G
            # Defines recordsize.. 16K | 32K | 64K | 128K (default) | and etc.
            recordsize: 16K
            sharenfs: on
            # standard (default) | always | disabled    sync: disabled
            # Controls whether the snapshots devices of zvol's are hidden or visible. hidden (default) | visible
            snapdev: visible
            # Controls whether the .zfs directory is hidden or visible in the root of the file system. hidden (default) | visible
            snapdir: visible
            state: present

        zfs_enable_monitoring: false
        # in percentage.
        zfs_monitoring_capacity_threshold: 80
        # in days.
        zfs_monitoring_scrub_max_age: 8
        zfs_monitoring_email_dest: root@localhost
        # Defines zpool(s) to manage
        zfs_pools:
          - name: tank
            mount: /tank #/data/beegfs/beegfs_oss/dev/HDD-TANK-01
            action: create
            #atime: on
            compression: lz4 # on | off (default) | lz4...
            # Define devices to create pool with...can define multiple by | sdb sdc sdd sde sdf | all on one line w/spaces
            devices:
              # - pci-0000:00:14.0-scsi-0:0:1:0 # iso9660
              - pci-0000:00:14.0-scsi-0:0:2:0
              - pci-0000:00:14.0-scsi-0:0:3:0
              - pci-0000:00:14.0-scsi-0:0:4:0
              - pci-0000:00:14.0-scsi-0:0:5:0
              - pci-0000:00:14.0-scsi-0:0:6:0
            type: raidz2
            state: present
              
          - name: tank
            mount: /tank #/data/beegfs/beegfs_oss/dev/HDD-TANK-01
            action: add
            devices:
              - pci-0000:00:14.0-scsi-0:0:8:0
              - pci-0000:00:14.0-scsi-0:0:9:0
              - pci-0000:00:14.0-scsi-0:0:10:0
              - pci-0000:00:14.0-scsi-0:0:11:0
              - pci-0000:00:14.0-scsi-0:0:12:0
            type: raidz2
            state: present

          - name: tank
            mount: /tank #/data/beegfs/beegfs_oss/dev/HDD-TANK-01
            action: add
            devices:
              - pci-0000:00:14.0-scsi-0:0:13:0
              - pci-0000:00:14.0-scsi-0:0:14:0
            type: spare
            state: present

