---
# tasks file for ansible-zfs
#- include: debian.yml
#  when: ansible_distribution == "Debian"

#- include: ubuntu.yml
#  when: ansible_distribution == "Ubuntu"

- name: install zfs
  package:
    name: "{{ zfs_packages }}"
    state: present
  register: zfs_install_zfs
  until: zfs_install_zfs is succeeded
  retries: 3

- include: manage_zfs.yml

- include: samba.yml
  when: zfs_enable_samba

- include: tune_zfs.yml
  when: >
        zfs_enable_performance_tuning is defined and
        zfs_enable_performance_tuning

- include: monitoring.yml
  when: zfs_enable_monitoring
